Raise minimum rust version to 1.42
Required by use of `matches!` in rustc-demangle.

    error[E0658]: use of unstable library feature 'matches_macro'
       --> rustc-demangle-0.1.21/src/v0.rs:700:20
        |
    700 |                 if matches!((quote, c), ('\'', '"') | ('"', '\'')) {
        |                    ^^^^^^^