Raise minimum tested compiler to 1.70
Required by clap 4.4.0.

    error: package `clap_derive v4.4.0` cannot be built because it
    requires rustc 1.70.0 or newer, while the currently active rustc
    version is 1.64.0